-- Migration: Create article_comment table for inline and general editorial comments
CREATE TABLE IF NOT EXISTS article_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  block_index INT,                 -- NULL = General Article comment; 0, 1, 2... = Paragraph index
  selected_text TEXT,              -- Snippet of paragraph text for reference
  content TEXT NOT NULL,           -- The comment body
  user_email TEXT NOT NULL,        -- Commenter email
  user_name TEXT,                  -- Optional display name
  parent_id BIGINT REFERENCES article_comment(id) ON DELETE CASCADE, -- For threaded replies
  is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast query retrieval
CREATE INDEX IF NOT EXISTS idx_article_comment_article_id ON article_comment(article_id);
CREATE INDEX IF NOT EXISTS idx_article_comment_parent_id ON article_comment(parent_id);
CREATE INDEX IF NOT EXISTS idx_article_comment_block_index ON article_comment(article_id, block_index);
